config/routes.rb
Rails.application.routes.draw do
  root to: "users#login"
  get 'register', to: 'users#register'
  get 'logout', to: 'users#logout'
  get 'login', to: 'users#login'
  resources :users do
    collection do
      match :register, via: [:get, :post]
      match :login, via: [:get, :post]
      get :logout
    end
  end

  resources :tasks, only: [:index, :create, :destroy] do
    member do
      post :change_status
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :description, presence: true, length: {in: 1..40}
  belongs_to :user
  enum status: [:start, :process, :done]
  scope :except_done, -> { where.not(status: statuses[:done])}
  before_save :set_status

  def set_status
    self.status = Task.statuses[:start] if self.new_record?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::SecurePassword
  has_secure_password
  validates :name, uniqueness: true, length: { in: 4..16 }
  validates :password, confirmation: true, length: { in: 8..16 }
  validate :complex_check

  has_many :tasks

  def complex_check
    errors.add(:password, 'should be contains at least 1 upper case, 1 lower case, 1 number') unless password =~ /[a-z]/ && password =~ /[A-Z]/ && password =~ /[0-9]/
    errors.add(:name, 'should not contains any special characters') if name =~ /[~|!|@|#|$|%|^|&|*|<|>|?]/
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :current_user, except: [:logout, :login, :register]

  def current_user
    @current_user ||= User.find(session[:user_id]) rescue nil
    redirect_to root_path if @current_user.blank?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:change_status, :destroy]
  before_action :all_tasks, only: [:index, :create]
  def index
    @task = Task.new(user_id: @current_user.id)
  end

  def create
    @task = Task.new(handle_params)
    respond_to do |format|
      @errors = @task.errors unless @task.save
      format.js { render :layout => false }
    end
  end

  def change_status
    new_status = case @task.status
    when 'start'
      'process'
    when 'process'
      'done'
    else
      'start'
    end
    @task.update(status: Task.statuses[new_status])
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def handle_params
    params.require(:task).permit(:user_id, :description, :status, :import, :urgent)
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def all_tasks
    @show_closed_task = params[:show_closed_task] == 'true'
    @tasks = if @show_closed_task
      Task.all
    else
      Task.except_done
    end.where(user_id: @current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_root, only: [:login]

  def login
    return if request.get?
    user = User.find_by(name: handle_params[:name])
    @user = user.authenticate(handle_params[:password]) if user.present?
    if @user
      session[:user_id] = @user.id
      redirect_to tasks_path
    else
      flash[:error] = 'Name or password was wrong'
      render :login
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def register
    return if request.get?
    @user = User.new(handle_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path
    else
      @errors = @user.errors
      render :register
    end
  end

  private

  def handle_params
    params.require(:users).permit(:name, :password, :password_confirmation)
  end

  def redirect_to_root
    redirect_to tasks_path if User.find_by(id: session[:user_id]).present?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def task_des_text_and_label(task)
    label_text, label = case task.status
    when 'start'
      ['open', 'lbl-primary']
    when 'process'
      ['process', 'lbl-success']
    when 'done'
      ['closed', 'lbl-default']
    else
      []
    end
    return label_text, label
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <title>AlignBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, url: tasks_path, method: :post, remote: true, html: {class: "form-horizontal"}) do |f| %>
  <% if @errors.try(:any?) %>
    <div id="error_explanation">
      <b>出现<%= @errors.count %>错误:</b>
      <ul>
      <% @errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id %>
  <div class="form-group row">
    <label for="description" class="col-md-4 col-form-label text-md-right">enter your code</label>
    <div class="col-md-6">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label for="import" class="col-md-4 col-form-label text-md-right">import</label>
    <div class="col-md-6">
      <%= f.label :import, "not import", value: "false"  %>
      <%= f.radio_button :import, false, checked: true  %>
      <%= f.label :import, "import" %>
      <%= f.radio_button :import, true %>
    </div>
  </div>
  <div class="form-group row">
    <label for="urgent" class="col-md-4 col-form-label text-md-right">urgent</label>
    <div class="col-md-6">
      <%= f.label :urgent, "not urgent", value: "false"  %>
      <%= f.radio_button :urgent, false, checked: true  %>
      <%= f.label :urgent, "urgent" %>
      <%= f.radio_button :urgent, true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-6 offset-md-4">
      <%= f.submit 'Add', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tasks/_task_list.html.erb
<style type="text/css">
.lbl {
    padding: .5rem 1rem;
    border-radius: .2rem;
    cursor: pointer;
    transition: all .3s;
    transition-timing-function: ease-in-out;
}

.lbl-default {
    background-color: rgb(116,120,141, 0.1);
    color: #74788d;
}

.lbl-default:hover {
    background-color: #74788d;
    color: #fff;
}

.lbl-success {
    background-color: rgba(10, 187, 135, 0.1);
    color: #0abb87;
}

.lbl-success:hover {
    background-color: #0abb87;
    color: #fff;
}

.lbl-danger {
    background-color: rgba(253,57,122,.1);
    color: #fd397a;
}

.lbl-danger:hover {
    background-color: #fd397a;
    color: #fff;
}

.lbl-primary {
    background-color: rgba(93,120,255,.1);
    color: #5d78ff;
}

.lbl-primary:hover {
    background-color: #5d78ff;
    color: #fff;
}

.lbl-warning {
    background-color: rgba(255,184,34,.1);
    color: #ffb822;
}

.lbl-warning:hover {
    background-color: #ffb822;
    color: #fff;
}

.lbl-block {
    display: block;
}
</style>
<div class="table-responsive" id="sailorTableArea">
  <table id="sailorTable" class="table table-striped table-bordered" width="100%">
    <thead></thead>
    <tbody>
      <% @tasks.each do |task| %>
        <% text, label = task_des_text_and_label(task) %>
        <tr>
          <td width="50%">
            <%= task.description %>
            <label class="lbl <%= label %>">
              <span><%= text %></span>
            </label>
          </td>
          <td width="15%">
            <label class="lbl <%= task.urgent ? 'lbl-danger' : 'lbl-default' %>"><span><%= task.urgent ? 'import' : 'not import' %></span></label>
          </td>
          <td width="15%">
            <label class="lbl <%= task.urgent ? 'lbl-warning' : 'lbl-default' %>"><span><%= task.urgent ? 'urgent' : 'not urgent' %></span></label>
          </td>
          <td>
            <% unless task.done? %>
              <%= link_to "#{task.start? ? 'start' : 'done'}", change_status_task_path(task.id), method: :post, class: 'btn btn-primary' %>
            <% end %>
            <%= link_to "delete", task_path(task.id), method: :delete, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/create.js.erb
$("#task_body").html("<%= escape_javascript(render 'task_list') %>");
$("#task_new").html("<%= escape_javascript(render 'form') %>");

app/views/tasks/index.html.erb
<body>
  <nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
    <div class="container">
      <a class="navbar-brand" href="#">Backlogs</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"       aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <span class="nav-link">Hi, <%= @current_user.name %> </span>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', '/logout', class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="cotainer">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <span>Tasks</span>
            <span style="float:right">
              <%= check_box_tag :show_closed_task, @show_closed_task, @show_closed_task %>
              <%= label_tag 'show closed tasks' %>
            </span>
          </div>
            <div class="card-body">
              <div id="task_body">
                <%= render "task_list" %>
              </div>
              <div id="task_new">
                <%= render 'form' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
<script>
  $(document).ready(function() {
    $('#show_closed_task').click(function(){
      var value = $('#show_closed_task').val()
      if (value === 'false') {
        window.location.href = "<%= tasks_path(show_closed_task: true) %>"
      } else {
        window.location.href = "<%= tasks_path(show_closed_task: false) %>"
      }
    })
  })
</script>

app/views/users/login.html.erb
<body>
<nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
  <div class="container">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Register', '/register', class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<main class="login-form">
  <div class="cotainer">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">Login</div>
            <div class="card-body">
              <%= form_for(:users, url: login_users_path, method: :post, html: {class: "form-horizontal"}) do |f| %>
                <% flash.each do |k, message| %>
                  <div class="alert alert-<%= k %>">
                    <strong><%= k.capitalize %></strong>: <%= message %>
                  </div>
                <% end %>
                <div class="form-group row">
                  <label for="email_address" class="col-md-4 col-form-label text-md-right">Name</label>
                  <div class="col-md-6">
                    <%= f.text_field :name, class: "form-control" %>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                  <div class="col-md-6">
                    <%= f.password_field :password, class: "form-control" %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-6 offset-md-4">
                    <%= f.submit 'Login', class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
</body>

app/views/users/register.html.erb
<body>
  <nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/register">Register</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <main class="login-form">
    <div class="cotainer">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header">Register</div>
              <div class="card-body">
                <%= form_for(:users, url: register_users_path, method: :post, html: {class: "form-horizontal"}) do |f| %>
                  <% if @errors.try(:any?) %>
                    <div id="error_explanation">
                      <b>出现<%= @errors.count %>错误:</b>
                      <ul>
                        <% @errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                      </div>
                  <% end %>
                  <div class="form-group row">
                    <label for="email_address" class="col-md-4 col-form-label text-md-right">Name</label>
                    <div class="col-md-6">
                      <%= f.text_field :name, class: "form-control" %>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                    <div class="col-md-6">
                      <%= f.password_field :password, class: "form-control" %>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="password" class="col-md-4 col-form-label text-md-right">Password Confirmation</label>
                    <div class="col-md-6">
                      <%= f.password_field :password_confirmation, class: "form-control" %>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-md-6 offset-md-4">
                      <%= f.submit 'Register', class: "btn btn-primary" %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  </body>